// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe7ukVHjygJqarv-egHXMAAJnR8ixoZVA',
    appId: '1:531357665699:web:20b533e3c04e1b1b653216',
    messagingSenderId: '531357665699',
    projectId: 'hackaton-189bb',
    authDomain: 'hackaton-189bb.firebaseapp.com',
    storageBucket: 'hackaton-189bb.appspot.com',
    measurementId: 'G-49B8B3DVPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCP4eYkkjb4Ql0FH0PLQV3DtU0pTfKcSI',
    appId: '1:531357665699:android:84d3bbaa9c14ddaa653216',
    messagingSenderId: '531357665699',
    projectId: 'hackaton-189bb',
    storageBucket: 'hackaton-189bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnS437GGbyDyEgCGfI807RwaAg_k8Mvwo',
    appId: '1:531357665699:ios:85af39b9449c91f0653216',
    messagingSenderId: '531357665699',
    projectId: 'hackaton-189bb',
    storageBucket: 'hackaton-189bb.appspot.com',
    iosClientId: '531357665699-umr62jtaevmsovhhlmv6tl7mf6d21p6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackaton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnS437GGbyDyEgCGfI807RwaAg_k8Mvwo',
    appId: '1:531357665699:ios:85af39b9449c91f0653216',
    messagingSenderId: '531357665699',
    projectId: 'hackaton-189bb',
    storageBucket: 'hackaton-189bb.appspot.com',
    iosClientId: '531357665699-umr62jtaevmsovhhlmv6tl7mf6d21p6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackaton',
  );
}
